name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - run: make

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            build/get_vcore
            build/get_vcore.sha256
